In [11]:
import sys
print(sys.version)

3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [5]:
import sys
print(sys.executable)
print(sys.path)

c:\Program Files\Python313\python.exe
['c:\\Program Files\\Python313\\python313.zip', 'c:\\Program Files\\Python313\\DLLs', 'c:\\Program Files\\Python313\\Lib', 'c:\\Program Files\\Python313', '', 'C:\\Users\\USER\\AppData\\Roaming\\Python\\Python313\\site-packages', 'c:\\Program Files\\Python313\\Lib\\site-packages']

In [12]:
import sys
print(sys.executable)
print(sys.version)

c:\Program Files\Python313\python.exe
3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [7]:
!where python
!jupyter kernelspec list

c:\Program Files\Python313\python.exe
C:\Users\USER\AppData\Local\Programs\Python\Python314\python.exe
C:\Users\USER\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\USER\AppData\Local\Python\bin\python.exe
Available kernels:
  ml_env     C:\Users\USER\AppData\Roaming\jupyter\kernels\ml_env
  ml_env2    C:\Users\USER\AppData\Roaming\jupyter\kernels\ml_env2
  py313      C:\Users\USER\AppData\Roaming\jupyter\kernels\py313
  python3    C:\Users\USER\AppData\Roaming\Python\share\jupyter\kernels\python3

In [8]:
import ipykernel
print(ipykernel.__file__)

C:\Users\USER\AppData\Roaming\Python\Python313\site-packages\ipykernel\__init__.py

In [9]:
import os
print(os.environ.get("VIRTUAL_ENV"))

None

In [1]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [1]:
import sys
print(sys.executable)
print(sys.prefix)

c:\Users\USER\ml_tf\Scripts\python.exe
c:\Users\USER\ml_tf

In [2]:
import numpy as np 
import tensorflow as tensorflow
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

Matplotlib is building the font cache; this may take a moment.

In [3]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],

    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],

    "sunlight_hours": [9, 8, 7, 4, 8, 2, 10, 3,
                       10, 12, 5, 9, 11, 2, 6, 1],

    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [4]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30               2            0
6            0.35             19              10            0
7            0.18             22               3            1
8            0.45             35              10            0
9            0.05             24              12            1
10           0.80             33               5            0
11           0.27             33               9            1
12           0.55             21              11            0
13           0.70             25               2            0
14           0.12             20               6            1
15           0.30             29               1            1

 # let's divide in x and y

In [5]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [6]:
X = df[["soil_moisture", "temperature_c", "sunlight_hours"]]
Y = df[['needs_water']]

## Normalisation
### Mean and Max scaler

In [7]:
X_min=X.min()
X_max = X.max()
X_scaled = (X-X_min)/(X_max-X_min + 1e-8)

In [ ]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.090909
6        0.400000         0.0000        0.818182
7        0.173333         0.1875        0.181818
8        0.533333         1.0000        0.818182
9        0.000000         0.3125        1.000000
10       1.000000         0.8750        0.363636
11       0.293333         0.8750        0.727273
12       0.666667         0.1250        0.909091
13       0.866667         0.3750        0.090909
14       0.093333         0.0625        0.454545
15       0.333333         0.6250        0.000000

In [8]:
# train and test split
X_train, X_test, y_train, y_test = train_test_split(
  X_scaled, Y, test_size=0.25, random_state=42,stratify=Y)

In [9]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [13]:
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history_full = model.fit(X_train,y_train, epochs=100, batch_size=len(X_train),verbose=1)
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=1,
        verbose=1
)
history_minibatch=model.fit(X_train,y_train,epochs=100,batch_size=100,verbose=1)

Epoch 1/100

3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 1s/step - accuracy: 0.5000 - loss: 0.6792 - val_accuracy: 0.5000 - val_loss: 0.6630
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 433ms/step - accuracy: 0.5000 - loss: 0.6779 - val_accuracy: 0.5000 - val_loss: 0.6615
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 377ms/step - accuracy: 0.5000 - loss: 0.6753 - val_accuracy: 0.5000 - val_loss: 0.6600
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 172ms/step - accuracy: 0.5000 - loss: 0.6732 - val_accuracy: 0.5000 - val_loss: 0.6586
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 194ms/step - accuracy: 0.5000 - loss: 0.6710 - val_accuracy: 0.5000 - val_loss: 0.6571
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 582ms/step - accuracy: 0.5000 - loss: 0.6692 - val_accuracy: 0.5000 - val_loss: 0.6558
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 601ms/step - accuracy: 0.5000 - loss: 0.6671 - val_accuracy: 0.5000 - val_loss: 0.6544
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 200ms/step - accuracy: 0.5000 - loss: 0.6654 - val_accuracy: 0.5000 - val_loss: 0.6531
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 719ms/step - accuracy: 0.5000 - loss: 0.6652 - val_accuracy: 0.5000 - val_loss: 0.6519
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 708ms/step - accuracy: 0.5000 - loss: 0.6630 - val_accuracy: 0.5000 - val_loss: 0.6507
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 496ms/step - accuracy: 0.5000 - loss: 0.6614 - val_accuracy: 0.5000 - val_loss: 0.6497
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 205ms/step - accuracy: 0.5000 - loss: 0.6602 - val_accuracy: 0.5000 - val_loss: 0.6486
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 1s/step - accuracy: 0.5000 - loss: 0.6586 - val_accuracy: 0.5000 - val_loss: 0.6475
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 6s/step - accuracy: 0.5000 - loss: 0.6575 - val_accuracy: 0.5000 - val_loss: 0.6463
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 457ms/step - accuracy: 0.5000 - loss: 0.6559 - val_accuracy: 0.5000 - val_loss: 0.6450
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 266ms/step - accuracy: 0.5000 - loss: 0.6540 - val_accuracy: 0.5000 - val_loss: 0.6437
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 241ms/step - accuracy: 0.5000 - loss: 0.6525 - val_accuracy: 0.5000 - val_loss: 0.6424
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 481ms/step - accuracy: 0.5000 - loss: 0.6510 - val_accuracy: 0.5000 - val_loss: 0.6412
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 166ms/step - accuracy: 0.5000 - loss: 0.6501 - val_accuracy: 0.7500 - val_loss: 0.6399
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step - accuracy: 0.5000 - loss: 0.6479 - val_accuracy: 0.7500 - val_loss: 0.6386
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.5000 - loss: 0.6464 - val_accuracy: 0.7500 - val_loss: 0.6374
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.5833 - loss: 0.6447 - val_accuracy: 0.7500 - val_loss: 0.6362
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 0.6667 - loss: 0.6434 - val_accuracy: 0.7500 - val_loss: 0.6349
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 174ms/step - accuracy: 0.7500 - loss: 0.6421 - val_accuracy: 0.7500 - val_loss: 0.6338
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7500 - loss: 0.6407 - val_accuracy: 0.7500 - val_loss: 0.6327
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.7500 - loss: 0.6397 - val_accuracy: 0.7500 - val_loss: 0.6317
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - accuracy: 0.7500 - loss: 0.6381 - val_accuracy: 0.7500 - val_loss: 0.6306
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7500 - loss: 0.6373 - val_accuracy: 0.7500 - val_loss: 0.6295
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.7500 - loss: 0.6372 - val_accuracy: 0.7500 - val_loss: 0.6284
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 121ms/step - accuracy: 0.7500 - loss: 0.6345 - val_accuracy: 0.7500 - val_loss: 0.6272
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.7500 - loss: 0.6338 - val_accuracy: 0.7500 - val_loss: 0.6259
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7500 - loss: 0.6324 - val_accuracy: 0.7500 - val_loss: 0.6247
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - accuracy: 0.7500 - loss: 0.6316 - val_accuracy: 0.7500 - val_loss: 0.6234
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.7500 - loss: 0.6303 - val_accuracy: 0.7500 - val_loss: 0.6223
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 0.7500 - loss: 0.6299 - val_accuracy: 0.7500 - val_loss: 0.6212
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 211ms/step - accuracy: 0.7500 - loss: 0.6288 - val_accuracy: 0.7500 - val_loss: 0.6201
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 180ms/step - accuracy: 0.7500 - loss: 0.6290 - val_accuracy: 0.7500 - val_loss: 0.6191
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.6667 - loss: 0.6272 - val_accuracy: 0.7500 - val_loss: 0.6180
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 103ms/step - accuracy: 0.6667 - loss: 0.6260 - val_accuracy: 0.7500 - val_loss: 0.6170
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.6667 - loss: 0.6255 - val_accuracy: 0.7500 - val_loss: 0.6159
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.6667 - loss: 0.6247 - val_accuracy: 0.7500 - val_loss: 0.6149
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 0.6667 - loss: 0.6245 - val_accuracy: 0.7500 - val_loss: 0.6138
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.6667 - loss: 0.6227 - val_accuracy: 0.7500 - val_loss: 0.6128
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.6667 - loss: 0.6228 - val_accuracy: 0.7500 - val_loss: 0.6117
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 106ms/step - accuracy: 0.6667 - loss: 0.6220 - val_accuracy: 0.7500 - val_loss: 0.6107
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.6667 - loss: 0.6206 - val_accuracy: 0.7500 - val_loss: 0.6097
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 231ms/step - accuracy: 0.6667 - loss: 0.6199 - val_accuracy: 0.7500 - val_loss: 0.6087
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 531ms/step - accuracy: 0.6667 - loss: 0.6191 - val_accuracy: 0.7500 - val_loss: 0.6076
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 429ms/step - accuracy: 0.6667 - loss: 0.6185 - val_accuracy: 0.7500 - val_loss: 0.6066
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 415ms/step - accuracy: 0.7500 - loss: 0.6175 - val_accuracy: 0.7500 - val_loss: 0.6057
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 234ms/step - accuracy: 0.7500 - loss: 0.6168 - val_accuracy: 1.0000 - val_loss: 0.6048
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 244ms/step - accuracy: 0.7500 - loss: 0.6158 - val_accuracy: 1.0000 - val_loss: 0.6039
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 279ms/step - accuracy: 0.7500 - loss: 0.6153 - val_accuracy: 1.0000 - val_loss: 0.6030
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 256ms/step - accuracy: 0.7500 - loss: 0.6155 - val_accuracy: 1.0000 - val_loss: 0.6020
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 407ms/step - accuracy: 0.7500 - loss: 0.6135 - val_accuracy: 1.0000 - val_loss: 0.6011
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 355ms/step - accuracy: 0.7500 - loss: 0.6139 - val_accuracy: 1.0000 - val_loss: 0.6002
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 404ms/step - accuracy: 0.7500 - loss: 0.6123 - val_accuracy: 1.0000 - val_loss: 0.5993
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 491ms/step - accuracy: 0.7500 - loss: 0.6111 - val_accuracy: 1.0000 - val_loss: 0.5984
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 396ms/step - accuracy: 0.7500 - loss: 0.6103 - val_accuracy: 1.0000 - val_loss: 0.5975
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 362ms/step - accuracy: 0.7500 - loss: 0.6107 - val_accuracy: 1.0000 - val_loss: 0.5966
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 260ms/step - accuracy: 0.7500 - loss: 0.6087 - val_accuracy: 1.0000 - val_loss: 0.5955
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 445ms/step - accuracy: 0.7500 - loss: 0.6081 - val_accuracy: 1.0000 - val_loss: 0.5944
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 627ms/step - accuracy: 0.7500 - loss: 0.6069 - val_accuracy: 1.0000 - val_loss: 0.5934
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 8s 2s/step - accuracy: 0.7500 - loss: 0.6057 - val_accuracy: 1.0000 - val_loss: 0.5923
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 952ms/step - accuracy: 0.7500 - loss: 0.6052 - val_accuracy: 1.0000 - val_loss: 0.5912
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 333ms/step - accuracy: 0.7500 - loss: 0.6038 - val_accuracy: 1.0000 - val_loss: 0.5898
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 424ms/step - accuracy: 0.7500 - loss: 0.6028 - val_accuracy: 1.0000 - val_loss: 0.5884
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 393ms/step - accuracy: 0.7500 - loss: 0.6018 - val_accuracy: 1.0000 - val_loss: 0.5871
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 308ms/step - accuracy: 0.7500 - loss: 0.6018 - val_accuracy: 1.0000 - val_loss: 0.5857
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 267ms/step - accuracy: 0.7500 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.5844
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 229ms/step - accuracy: 0.7500 - loss: 0.5994 - val_accuracy: 1.0000 - val_loss: 0.5830
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 300ms/step - accuracy: 0.7500 - loss: 0.5979 - val_accuracy: 1.0000 - val_loss: 0.5816
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 350ms/step - accuracy: 0.7500 - loss: 0.5973 - val_accuracy: 1.0000 - val_loss: 0.5802
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 248ms/step - accuracy: 0.7500 - loss: 0.5964 - val_accuracy: 1.0000 - val_loss: 0.5788
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 269ms/step - accuracy: 0.7500 - loss: 0.5958 - val_accuracy: 1.0000 - val_loss: 0.5775
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - accuracy: 0.7500 - loss: 0.5938 - val_accuracy: 1.0000 - val_loss: 0.5761
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 388ms/step - accuracy: 0.7500 - loss: 0.5932 - val_accuracy: 1.0000 - val_loss: 0.5748
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 171ms/step - accuracy: 0.7500 - loss: 0.5918 - val_accuracy: 1.0000 - val_loss: 0.5735
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 232ms/step - accuracy: 0.7500 - loss: 0.5912 - val_accuracy: 1.0000 - val_loss: 0.5721
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 232ms/step - accuracy: 0.7500 - loss: 0.5898 - val_accuracy: 1.0000 - val_loss: 0.5708
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 351ms/step - accuracy: 0.7500 - loss: 0.5893 - val_accuracy: 1.0000 - val_loss: 0.5694
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 582ms/step - accuracy: 0.7500 - loss: 0.5879 - val_accuracy: 1.0000 - val_loss: 0.5677
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 240ms/step - accuracy: 0.7500 - loss: 0.5875 - val_accuracy: 1.0000 - val_loss: 0.5660
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 317ms/step - accuracy: 0.7500 - loss: 0.5848 - val_accuracy: 1.0000 - val_loss: 0.5646
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 355ms/step - accuracy: 0.7500 - loss: 0.5845 - val_accuracy: 1.0000 - val_loss: 0.5634
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 695ms/step - accuracy: 0.7500 - loss: 0.5818 - val_accuracy: 1.0000 - val_loss: 0.5621
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 836ms/step - accuracy: 0.7500 - loss: 0.5808 - val_accuracy: 1.0000 - val_loss: 0.5610
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - accuracy: 0.7500 - loss: 0.5807 - val_accuracy: 1.0000 - val_loss: 0.5599
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 2s/step - accuracy: 0.7500 - loss: 0.5789 - val_accuracy: 1.0000 - val_loss: 0.5587
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 895ms/step - accuracy: 0.7500 - loss: 0.5775 - val_accuracy: 1.0000 - val_loss: 0.5576
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 901ms/step - accuracy: 0.7500 - loss: 0.5762 - val_accuracy: 1.0000 - val_loss: 0.5565
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 811ms/step - accuracy: 0.7500 - loss: 0.5758 - val_accuracy: 1.0000 - val_loss: 0.5554
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 967ms/step - accuracy: 0.7500 - loss: 0.5743 - val_accuracy: 1.0000 - val_loss: 0.5543
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 495ms/step - accuracy: 0.7500 - loss: 0.5735 - val_accuracy: 1.0000 - val_loss: 0.5532
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 326ms/step - accuracy: 0.7500 - loss: 0.5723 - val_accuracy: 1.0000 - val_loss: 0.5521
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 321ms/step - accuracy: 0.7500 - loss: 0.5712 - val_accuracy: 1.0000 - val_loss: 0.5509
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 421ms/step - accuracy: 0.7500 - loss: 0.5698 - val_accuracy: 1.0000 - val_loss: 0.5498
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 1s/step - accuracy: 0.7500 - loss: 0.5690 - val_accuracy: 1.0000 - val_loss: 0.5487
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 281ms/step - accuracy: 0.7500 - loss: 0.5682 - val_accuracy: 1.0000 - val_loss: 0.5478
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 286ms/step - accuracy: 0.7500 - loss: 0.5673 - val_accuracy: 1.0000 - val_loss: 0.5468